[mqtt]
host = "mqtt"
port = 1883
username = ""
password = ""

[sensors]
blacklist = []
use_blacklist = false
whitelist = []
use_whitelist = false
debug_print = false

[publish]
discovery = true
decoded_data = true
raw_data = false
