name: Build and publish Docker Image

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  docker:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract version
        id: extract_version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build image
        run: |
          docker build -t thomsva/ruuvi-rust-mqtt:latest .

      - name: Tag image
        run: |
          if [ "${RELEASE_TAG}" != "latest" ]; then
            docker tag thomsva/ruuvi-rust-mqtt:latest thomsva/ruuvi-rust-mqtt:${RELEASE_TAG}
          fi

      - name: Push image
        run: |
          docker push thomsva/ruuvi-rust-mqtt:latest
          if [ "${RELEASE_TAG}" != "latest" ]; then
            docker push thomsva/ruuvi-rust-mqtt:${RELEASE_TAG}
          fi


